### ISSUE TITLE
Implementation of "pairwise mode", similar to Circuitscape

### ISSUE THREAD

**Issue by xgirouxb** [Pbleonard/GFlow#13]
In Circuitscape, there is a "pairwise mode" option which allows you to calculate effective resistances between all your nodes using `n` runs instead of `n(n-1)/2` runs. Is there a similar setting hiding in the flags of the current implementation of gflow, or is the goal of the current version strictly to produce cumulative current maps based on random nodes?

I noticed that in your ipython notebooks there is some code to calculate one-to-all LCPs based on Dijkstra's algorithm in a resistance surface. Is the intent eventually to implement a "pairwise mode" functionality by: 1) computing a resistance surface using random nodes until it converges to the desired precision, then 2) computing pairwise effective resistances between nodes of interest using Dijkstra's algorithm?

Thanks!

**Comment by Pbleonard** [comment]
@xgirouxb Pairwise mode is enabled in GFlow by simply not including 2 optional flags: the ```converge_at``` and the ```shuffle_node_pairs```. If absent, the software will calculate all pairwise. The optional flags exist for problems that are large enough that someone doesn't want to wait for all pairwise or does not have enough resources and that is where the random node pair calculations come into play.

To your other question, a future ```effective resistance only``` mode that is ```n``` runs is likely
