### ISSUE TITLE
Error in reproducing example: TMPDIR environmental variable 

### ISSUE THREAD

**Issue by fgabriel1891** [Pbleonard/GFlow#17]
Hi! I'm trying to replicate the example on a Mac OS Sierra laptop. However after compiling and trying to run the example, I get the following error. 

    Fri Jun 30 14:59:39 CEST 2017
    PMIx has detected a temporary directory name that results
    in a path that is too long for the Unix domain socket:

    Temp dir: /var/folders/bp/988s8lhn3zg556kd22vmxmx00000gn/T/openmpi-sessions-501@wcw-
    stud-145-109-27-212_0/17726

    Try setting your TMPDIR environmental variable to point to
    something shorter in length

I'm not very clear in the "# Set and add PETSc to PATH" step. Should I edit and provide the direction of the folder in which GFlow was compiled? 

Thanks for your answer. 

Gabriel

**Comment by Pbleonard** [comment]
@fgabriel1891 Did you use a package manager to install PETSC or do you know the installation folder? If using aptitude as described [here](https://github.com/Pbleonard/GFlow) then the install location will be similar to this `PETSC_DIR=/usr/local/Cellar/petsc/3.7.3/real`

**Comment by eduffy** [comment]
@fgabriel1891 - I've never seen that error before, but looks to be documented here:  https://www.open-mpi.org/faq/?category=osx#startup-errors-with-open-mpi-2.0.x

Sounds like you can run `export TMPDIR=/tmp` and be good to go.

**Comment by fgabriel1891** [comment]
Sorry I was out of this issue for a little bit. After setting export TMPDIR=/tmp I was indeed able to reproduce the example! Many Thanks!
