### ISSUE TITLE
Computing connectivity for a batch of resistance maps

### ISSUE THREAD

**Issue by RMarrec** [Pbleonard/GFlow#19]
Hi. I would like to compute connectivity for 50 ASCII resistance maps (10 maps at 5 different resolutions). I use the same node file for all maps at a given resolution (ie 5 node files). Is there a way to run gflow for all maps at once, and not do it manually? Maybe by running the script in a loop? I do not know how to code in linux, that's why I am asking for help!
Thank you if you can help me. Ronan.

**Comment by Pbleonard** [comment]
Hi Ronan, taking this offline. Email sent.

Cheers,
Paul

On Tuesday, July 11, 2017, RMarrec <notifications@github.com> wrote:

> Hi. I would like to compute connectivity for 50 ASCII resistance maps (10
> maps at 5 different resolutions). I use the same node file for all maps at
> a given resolution (ie 5 node files). Is there a way to run gflow for all
> maps at once, and not do it manually? Maybe by running the script in a
> loop? I do not know how to code in linux, that's why I am asking for help!
> Thank you if you can help me. Ronan.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <http://internal/tab?url=https%3A%2F%2Furldefense.proofpoint.com%2Fv2%2Furl%3Fu%3Dhttps-3A__github.com_Pbleonard_GFlow_issues_19%26d%3DDwMCaQ%26c%3DNgd-ta5yRYsqeUsEDgxhcqsYYY1Xs5ogLxWPA_2Wlc4%26r%3DJFNhIwKlMoiVOcCCQu5eBCOCKlJciwyZGlNhbQn1DPk%26m%3DE21AFNv65ZUSOZt1PtSbdtkNI65GhSw4YXc0Fn3XjaI%26s%3DTc8-2gq0RkJ2C8HtDkEpV7_TNxji1rbRSrYKU6zaINI%26e%3D&referrer=https%3A%2F%2Fmail.google.com%2Fmail%2Fmu%2Fmp%2F66%2F%23co&target=_blank>,
> or mute the thread
> <http://internal/tab?url=https%3A%2F%2Furldefense.proofpoint.com%2Fv2%2Furl%3Fu%3Dhttps-3A__github.com_notifications_unsubscribe-2Dauth_ASoaTBHCvmlNIL-2DHt-5FisiyT5mV-5FCSKP3ks5sM76JgaJpZM4OUojB%26d%3DDwMCaQ%26c%3DNgd-ta5yRYsqeUsEDgxhcqsYYY1Xs5ogLxWPA_2Wlc4%26r%3DJFNhIwKlMoiVOcCCQu5eBCOCKlJciwyZGlNhbQn1DPk%26m%3DE21AFNv65ZUSOZt1PtSbdtkNI65GhSw4YXc0Fn3XjaI%26s%3DcFBu1UjyDoOyLtRUyDTk-qDqGIPH-DamKQBSQ7GGG68%26e%3D&referrer=https%3A%2F%2Fmail.google.com%2Fmail%2Fmu%2Fmp%2F66%2F%23co&target=_blank>
> .
>


-- 
Sent from Gmail Mobile
