### ISSUE TITLE
GFlow: Customizable convergence criterion

### ISSUE THREAD

**Issue by Pbleonard** [Pbleonard/GFlow#2]
User input: desired number of 9s or 1-Delta Convergence.
Update execute script comments with flag info.

**Comment by eduffy** [comment]
Are you wanting to provide the convergence as either "4N" or "0.0001" or "1e-4" or all of the above?

**Comment by Pbleonard** [comment]
MS uses # of 9s convention. That should do.

**Comment by eduffy** [comment]
I committed an untested version of this to ead64df. Please give it a shot when you have a chance to run a real world problem on the cluster.  The new flag is `-converge_at` and you may supply the convergence factor in any of the 3 formats above.

**Comment by eduffy** [comment]
Commit 35c0b84 should have this final fixed for realzies this time (thanks for the smaller input file).
