### ISSUE TITLE
Run Log

### ISSUE THREAD

**Issue by Pbleonard** [Pbleonard/GFlow#6]
I noticed when testing `converge_at` that no log files were printed after a completed run. Is there a log flag?

**Comment by eduffy** [comment]
No. Since I always ran this in PBS the terminal output was automatically redirected to a file.

**Comment by Pbleonard** [comment]
Gotcha. I think that would be the only way for us to collect R_eff?

**Comment by eduffy** [comment]
Okay, now I see what you're getting at.  I'll into this (hopefully on Sunday)

**Comment by eduffy** [comment]
New flag `-effective_resistance <path to log>` to support this.  See 6161a09.
