### ISSUE TITLE
[gview] Statistical breaks

### ISSUE THREAD

**Issue by eduffy** [Pbleonard/GFlow#7]
@Pbleonard - Are these the breaks you're wanting?

https://en.wikipedia.org/wiki/Chebyshev%27s_inequality#Probabilistic_statement

**Comment by Pbleonard** [comment]
@eduffy That certainly looks like one interesting way to view. Might be applicable given different underlying distributions. These are more what I was thinking (prolly easier and more common) but I like where you're going:
https://saylordotorg.github.io/text_essentials-of-geographic-information-systems/s10-03-data-classification.html

**Comment by eduffy** [comment]
Thanks .. that looks helpful.

**Comment by Pbleonard** [comment]
The 4 reviewed are super common and cover most distributions in some way. For us I think there are probably 2 here that would be useful:

1. Standard Deviation
2. Natural Breaks

and Geometric Interval would likely be super useful here (sorry doesn't say how to do it here but should be able to find easily):
http://wiki.gis.com/wiki/index.php/Geometric_Interval_Classification

**Comment by eduffy** [comment]
Great, thanks... I'll start working on implementing these in the viewer

sent from my mobile.

**Comment by eduffy** [comment]
I'm going to implement these first in a Python notebook, to make it easier to compare approaches.  3562eac is a start ... includes the two already in `gview`, plus the Standard Deviation calculation.

**Comment by eduffy** [comment]
I've updated the notebook.

1. Geometric Interval is parameterized (if I'm reading the docs correctly, it's pretty close to what `gview` was already doing)
2. I found a C library with a Python interface to calculate the Jenks classes, but it was overheating my laptop.  You may have more luck on your desktop. You need to install an additional package from here: https://github.com/perrygeo/jenks
3. I've created breaks so that each color class gets the same number of pixels (ie, equal area).  It's interesting, but probably over exaggerates the current flow. 11 of 12 breaks appear in the first 3% of Amp values.

**Comment by Pbleonard** [comment]
Still traveling, will try to check this out on road today.

On Fri, Oct 7, 2016 at 8:22 PM, Edward Duffy <notifications@github.com>
wrote:

> I've updated the notebook.
>
>    1. Geometric Interval is parameterized (if I'm reading the docs
>    correctly, it's pretty close to what gview was already doing)
>    2. I found a C library with a Python interface to calculate the Jenks
>    classes, but it was overheating my laptop. You may have more luck on your
>    desktop. You need to install an additional package from here:
>    https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_perrygeo_jenks&d=CwIFaQ&c=Ngd-ta5yRYsqeUsEDgxhcqsYYY1Xs5ogLxWPA_2Wlc4&r=Q4yGZXjzxPif2Z3iOxZx8njbr77-Yk0Z8PVV66EHG7VP8h4MRa_SZq0fu2Rv79QGomB7ydo49a4I1MqoTtZ6ofqdYwG12FXgs-1ZiVw1FZMLHR7vJXZ_Qg2R7GXuq0Mck4RHmjQ7M8HugChtiWnvew&m=ytNz1b6q-l8dVfrfigC6_UGV3pde2lT8DIkek7oT4QM&s=6GagSUa2lYe1PmmLBBpBoPGruLqt3qfEwYR2d2wwnxA&e= 
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_perrygeo_jenks&d=CwMFaQ&c=Ngd-ta5yRYsqeUsEDgxhcqsYYY1Xs5ogLxWPA_2Wlc4&r=JFNhIwKlMoiVOcCCQu5eBCOCKlJciwyZGlNhbQn1DPk&m=5VAnWxOW9i9aWmduAy3uhLtwIPweEE_eu3MfxDK7p9I&s=b4V7kHzbGVcz5xk_815bxj72Ce1b2A3w548HZTqAdhM&e=>
>    3. I've created breaks so that each color class gets the same number
>    of pixels (ie, equal area). It's interesting, but probably over exaggerates
>    the current flow. 11 of 12 breaks appear in the first 3% of Amp values.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Pbleonard_GFlow_issues_7-23issuecomment-2D252389333&d=CwMFaQ&c=Ngd-ta5yRYsqeUsEDgxhcqsYYY1Xs5ogLxWPA_2Wlc4&r=JFNhIwKlMoiVOcCCQu5eBCOCKlJciwyZGlNhbQn1DPk&m=5VAnWxOW9i9aWmduAy3uhLtwIPweEE_eu3MfxDK7p9I&s=xFhlI4qu6PDhfrDuRHJjI0OBpihJg-bdcn2e1CzJJE0&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ASoaTGjn5DogYOBa7xe9JCtqRqKvLXLPks5qxuJCgaJpZM4KME-2Db&d=CwMFaQ&c=Ngd-ta5yRYsqeUsEDgxhcqsYYY1Xs5ogLxWPA_2Wlc4&r=JFNhIwKlMoiVOcCCQu5eBCOCKlJciwyZGlNhbQn1DPk&m=5VAnWxOW9i9aWmduAy3uhLtwIPweEE_eu3MfxDK7p9I&s=1XLQK_hOnlL9tTMNuolZ86hnKuX3XCcb6Cv7JID8d4Y&e=>
> .
>



-- 
Paul Leonard, PhD
School of Agricultural, Forest, and Environmental Sciences
Clemson University
245 Lehotsky Hall
Office: (864) 656-4823
conservationcomputing.com
